version: '3.1'

# it is docker-compose version 3.1, same file can be used with docker swarm, with small change
# changes such as, docker swarm does not use bridge network, it uses overlay network (overlay networkspans cross mutiple noed machines)
# we just need to add deploy param in this file.

services:

    mysql:
        image: mysql:5.6.41
        restart: always
        environment:
            MYSQL_DATABASE: keycloak
            MYSQL_USER: keycloak
            MYSQL_PASSWORD: passport1
            MYSQL_ROOT_PASSWORD: passport1
        volumes:
            - 'D:/programes/sqldata:/var/lib/mysql'
        networks:
            - app-network

    # mysql admin website
#    adminer:
#        image: adminer
#        restart: always
#        ports:
#            - 8082:8080
#        networks:
#            - app-network
#        deploy:
#            replicas: 5
##            resources:
#            limits:
#                cpus: "0.1"
##                memory: 50M
#            restart_policy:
#            condition: on-failure

    keycloak:
        image: jboss/keycloak:4.4.0.Final
        restart: always
        depends_on:
            - mysql
        environment:
            # postgres, mysql, mariadb
            DB_VENDOR: mysql
            # hostname of database
            DB_ADDR: mysql
            DB_DATABASE: keycloak
            DB_USER: keycloak
            DB_PASSWORD: passport1
            PROXY_ADDRESS_FORWARDING: "true"
        # following ports line not for production
        ports:
            - 8080:8080
        networks:
            - app-network         
            
            
networks:
  app-network:
    external: true      
   
